### ISSUE TITLE
coverage.py on Circle Ci example

### ISSUE THREAD

**Issue by sfdye** [codeclimate/test-reporter#223]
I am trying to use coverage.py with [pytest-cov](https://github.com/pytest-dev/pytest-cov),

on Circle CI build, the coverage runs without an issue, however it's not able to find the .coverage result to upload to Code Climate:

Error message:
```
Results (5.38s):
      20 passed
ERRO[0000] could not find coverage file 
could not find any files in search paths for coverage.py. search paths were: , coverage.xml 
Error: could not find any files in search paths for coverage.py. search paths were: , coverage.xml
```

Can you give an working example for Python/coverage.py?

My Circle CI `config.xml`:

```
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.5.4
        environment:
          CC_TEST_REPORTER_ID: XXX
      - image: circleci/postgres:9.6.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
      - run:
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            ./cc-test-reporter before-build
      - run:
          command: |
            . venv/bin/activate
            py.test --cov=proj --cov-config .coveragerc
            ./cc-test-reporter format-coverage -t coverage.py -o ./.coverage
            ./cc-test-reporter upload-coverage
      - run:
          command: |
            ./cc-test-reporter after-build --exit-code $?
      - store_artifacts:
          path: test-reports/
          destination: tr1
```

My `.coveragerc`
```
[run]
include = proj/*
omit = *migrations*, *tests*
plugins =
    django_coverage_plugin
```
