### ISSUE TITLE
Documentation for usage with multiple test suites run in parallel

### ISSUE THREAD

**Issue by streetlogics** [codeclimate/test-reporter#229]
Mentioned here - https://github.com/codeclimate/ruby-test-reporter/issues/134#issuecomment-330916664, it seems that when one is using two different test suites and parallelizing those tests that configuring things gets a bit tricky.  I played around with a few different circleci configs trying to get it working (using this as a starting point https://docs.codeclimate.com/docs/circle-ci-test-coverage-example), but it kept wanting to run every test instead of a subset of the tests for that specific container being parallelized.  Do you guys have an example for getting this working where the existing circle test section looks like this for parallelization and distributing tests evenly according to the time it takes to run them:

```
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/cucumber:
        parallel: true
    -  PRECOMPILE=true bundle exec cucumber --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber:
        parallel: true
        files:
          - features/*.feature
    - bundle exec rspec --format doc --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec.xml:
        parallel: true
        files:
          - spec/**/*_spec.rb
```
