### ISSUE TITLE
golang + travis code coverage setup

### ISSUE THREAD

**Issue by jdel** [codeclimate/test-reporter#292]
After a couple hours spent struggling with the not-so-uo-to-date documentation, I'd like to share the config that works for me.

> .travis.yml
```
language: go
go:
  - 1.9
install:
  - go get -v github.com/golang/dep/cmd/dep
  - go get -v github.com/codeclimate/test-reporter
  - cd $GOPATH/src/github.com/golang/dep/cmd/dep && git checkout tags/v0.4.1 && go install
  - cd $GOPATH/src/github.com/codeclimate/test-reporter && git checkout tags/v0.4.3 && go install
  - cd - && dep ensure -v -vendor-only
before_script:
  - test-reporter before-build
script:
  - go test -coverprofile c.out
after_script:
  - test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
env:
  global:
    - secure: [REDACTED]
```

I am happy to submit a PR to update documentation is somebody points me to the files to update.
