### ISSUE TITLE
Cannot unmarshal number

### ISSUE THREAD

**Issue by bmulholland** [codeclimate/test-reporter#314]
To work around the issue in #313, I'm trying to use a JSON formatter instead. It's not entirely clear what "SimpleCov" means in terms of file format, but from the examples in this project I'm assuming that means SimpleCov JSON. Thus I've switched from Lcov formatter to JSON formatter, specifically https://github.com/vicentllongo/simplecov-json

The input file is valid JSON (I checked) but calling format-coverage on it is throwing an error I don't understand.

The entire debug output is:

```
DEBU[0000] coverage path coverage/cucumber/coverage.json 
DEBU[0000] using formatter simplecov                    
DEBU[0000] checking search path coverage/cucumber/coverage.json for simplecov formatter 
DEBU[0000] couldn't load committed at from ENV, trying git... 
Error: json: cannot unmarshal number into Go value of type simplecov.input
```

**Comment by bmulholland** [comment]
Hi @ale7714, This is a workaround for my project, but isn't it still a bug in test-reporter? It's not using any workaround on test-reporter, simply attempting to parse Simplecov coverage files.

**Comment by ale7714** [comment]
@bmulholland Hi, I don't think is a bug on the `test-reporter`. We format directly the output from the [simplecov gem](https://github.com/colszowka/simplecov) (specifically the `.resulset.json` file). 

You can read more about supported formats on our doc page: https://docs.codeclimate.com/docs/configuring-test-coverage#section-supported-languages-and-formats

Let me know if you have any further question.

**Comment by bmulholland** [comment]
@ale7714 Hmm - I've read that document, and I see that it uses SimpleCov, but I don't see how to configure SimpleCov and the test reporter. Is there an example of how to set it up?

As I mentioned in the above issue, I couldn't figure that out. I dug in, found https://github.com/codeclimate/test-reporter/blob/master/formatters/simplecov/simplecov-example.json, and assumed that meant that I needed a JSON output of SimpleCov's results. Sounds like that's wrong...

**Comment by ale7714** [comment]
@bmulholland 
High level overview you would setup your coverage tool (in your case simplecov) as you normally do. On your CI and after running your test, you will the `test-reporter` to format and upload. Here's a very general example:
```
machine:
  environment:
    CC_TEST_REPORTER_ID: ...

dependencies:
  post:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

test:
    - ./cc-test-reporter before-build
    - rspec
    - ./cc-test-reporter after-build --exit-code $EXIT_CODE
```

There are couple of examples under https://github.com/codeclimate/test-reporter/tree/master/examples.
