### ISSUE TITLE
Missing Coverage with TravisCI, Jest

### ISSUE THREAD

**Issue by stevenAtGeneralUI** [codeclimate/test-reporter#341]
I'm having trouble getting code coverage to be displayed through Code Climate.  I have used the `---debug` flag, and it appears to have successfully created and POSTed `codeclimate.json`.

I'm using Jest, which outputs lcov to `./coverage`.  From package.json:
```
"collectCoverage": true,
"coverageReporters": ["lcov"]
```
Here is my `.travis.yml`:
```
env:
  global:
    - CC_TEST_REPORTER_ID=ec3a169f7a2343e831cf13099e83f63e510fde66d7c1e94090cd57c868647ebb
language: node_js
node_js:
  - 9.4.0
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:coverage
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
```
The `after-build` steps reports:
```Test report uploaded successfully to Code Climate```

In Code Climate the initial umbrella icon changed to a dashed line:
![image](https://user-images.githubusercontent.com/16825244/40737564-fc93bbb6-63f5-11e8-8611-7cc54555f46f.png)

**Comment by stevenAtGeneralUI** [comment]
Here is some relevant info from `--debug`:
```
INFO[0000] trimming with prefix /home/travis/build/generalui/MyProject/ 
DEBU[0000] getting git blob_id for source file test_data/objectGenerators.tsx 
DEBU[0000] codeclimate.json content: {
  "ci_service": {
    "branch": "trying-to-fix-coverage-reporting",
    "build_identifier": "126730403",
    "build_url": "",
    "commit_sha": "db4ecdde8c223aa9830046434364d005c18e995d",
    "committed_at": 1527701381,
    "name": "true"
  },
  "environment": {
    "gem_version": "2.7.7",
    "package_version": "",
    "pwd": "/home/travis/build/generalui/MyProject",
    "prefix": "/home/travis/build/generalui/MyProject",
    "rails_root": "",
    "reporter_version": "0.6.0",
    "simplecov_root": ""
  },
  "git": {
    "branch": "trying-to-fix-coverage-reporting",
    "head": "db4ecdde8c223aa9830046434364d005c18e995d",
    "committed_at": 1527701381
  },
  "covered_percent": 17.333333333333336,
  "covered_strength": 0,
  "line_counts": {
    "missed": 3348,
    "covered": 702,
    "total": 4050
```

**Comment by davehenton** [comment]
Hey @stevenAtGeneralUI , sorry for the delay in getting to this. Taking a look our backend, I can confirm that we're receiving valid test payloads for your repo. However, we haven't yet received a payload from your default branch. Currently, we only display coverage info for the default branch in the UI. Coverage info for non-default branches is visible in Github by using our [browser extension](codeclimate.com/browser-extension). Once you upload a coverage payload from your default branch, let me know if you're still failing to see that info as expected. Thanks.

**Comment by ianpaschal** [comment]
I believe I'm experiencing this issue as well.

I'm basing this off of the Travis CI set-up described here:
https://docs.codeclimate.com/docs/travis-ci-test-coverage

My `travis.yml`:

```
env:
  global:
    - CC_TEST_REPORTER_ID=575206a0cd09b1027a40c9a0fb71da087210b8ec433c80e9136a1345de5cc842
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm run test
  - npm run bundle
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
```

Doesn't seem to work at all; I just see the umbrella for configuring code coverage forever.

FYI the information on configuring code coverage is pretty buried. I was rather annoyed to click on the configure code coverage button and see my token and basically zero info on how to do it. For that, I had to go to the docs, and from there, I had to very carefully read to find a small link to examples and to find the Travis CI example. Which doesn't work. Bummer.
