### ISSUE TITLE
Possible to use this with Github Workflow?

### ISSUE THREAD

**Issue by AdrianMF** [codeclimate/test-reporter#406]
I am beginning to migrate my CI to a Github workflow. Is it possible to use this? I haven't been able to find any documentation.

**Comment by textbook** [comment]
Do you mean GitHub Actions? Have you tried https://github.com/marketplace/actions/code-climate-coverage-action?

**Comment by guilhermearaujo** [comment]
I too am having trouble getting CodeClimate to report the coverage status for a pull request.

The action @textbook mentioned uses this code to provide the env vars that `cc-test-report` requires:

```js
function prepareEnv() {
  const env = process.env as { [key: string]: string };

  if (process.env.GITHUB_SHA !== undefined)
    env.GIT_COMMIT_SHA = process.env.GITHUB_SHA;
  if (process.env.GITHUB_REF !== undefined)
    env.GIT_BRANCH = process.env.GITHUB_REF;

  return env;
}
```

However, in my tests `GITHUB_SHA` and `GITHUB_REF` do not contain  the expected values.
The SHA hash is not the same as the last commit, and the REF is not the branch name, but it equals `refs/pull/<pr id>/merge` instead.

Without these values (or at least one of them), the pull request checks will stay eternally stuck at:

> **codeclimate/diff-coverage** Expected — Waiting for status to be reported
> **codeclimate/total-coverage** Expected — Waiting for status to be reported


This is an example of a workflow for a Rails project:

```yaml
jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install bundler
        run: gem install bundler -v '<2'

      - name: Install dependencies
        run: bundle install

      - name: Prepare for test
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          GIT_BRANCH=$GITHUB_REF GIT_COMMIT_SHA=$GITHUB_SHA ./cc-test-reporter before-build

      - name: Unit test with Rspec test suite
        # Coverage will be generated while running the specs using SimpleCov
        run: bundle exec rspec --format progress --profile

      - name: Report coverage
        run: GIT_BRANCH=$GITHUB_REF GIT_COMMIT_SHA=$GITHUB_SHA ./cc-test-reporter after-build -t simplecov --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
```

**Comment by robwold** [comment]
@guilhermearaujo I tried to use your solution and got this error:
```
fatal: ambiguous argument 'origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: response from https://api.codeclimate.com/v1/test_reports.
HTTP 422: is invalid
```
Reading your post again more carefully I noticed the stipulation about the event being a pull request, and this was triggered by a commit. Could that cause this issue?

**Comment by guilhermearaujo** [comment]
@robwold I didn't stop to analyse it in depth, but I'd guess it is.
When you only push a commit, and evaluate `git rev-parse origin/$GITHUB_HEAD_REF`, I'd say that `GITHUB_HEAD_REF` is blank, therefore can't rev-parse `origin/<nothing>`

**Comment by deivid-rodriguez** [comment]
Hei! So I had the same issues mentioned here, and found the workaround given a good starting point to fix my cases. Let me share my findings in case it helps others.

The `GIT_BRANCH=$GITHUB_HEAD_REF GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF) ./cc-test-reporter` is good, but has some gotchas:

* The `GITHUB_HEAD_REF` ref needs to be fetched, otherwise you'll get the error mentioned by @robwold. If you're using `actions/checkout@v1` to checkout your code, this is fetched by default, so no problem. If your using `actions/checkout@v2` or higher, this is a problem though. The workaround is to do something like `git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF` right before. See https://github.com/actions/checkout/issues/93, which suggests this workaround.

* The `upload-coverage` and `sum-coverage` commands, don't use git information from the environment, but pick it up from the existing reports. So if you're using a `format-coverage` -> `sum-coverage` -> `upload-coverage` workflow, make sure you pass the proper git variables to the `format-coverage` command.

**Comment by deivid-rodriguez** [comment]
Here is the working workflow: https://github.com/deivid-rodriguez/pry-byebug/blob/377e5b7d229a157bb896f21d776f71fc389a5c00/.github/workflows/ubuntu.yml

**Comment by deivid-rodriguez** [comment]
Unfortunately, it doesn't seem to be working for PRs coming from external forks :(

**Comment by awentzel** [comment]
It feels as if GitHub variables should not be required to use cc-test-reporter.  If they exist great, but, how do I locally test my scripts (executing on a mono-repository) when this is tightly coupled to GitHub / Actions / etc?

**Comment by Cielquan** [comment]
I tested a bit around a found a way to get the COMMIT_SHA for internal PRs and fork PR.

For a PR Github creates a merge commit (on/with a detached HEAD) and the commit message (cmt-msg) is the key. The cmt-msg is in the format: `Merge <sha of latest commit on branch to merge> into <sha of latest commit of branch to merge into>`. So you just have to get the cmt-msg and extract the SHA. I created a job to do this for me so I could grab the ENVVAR from this job#s outputs:

```yaml
env:
  default_python_version: 3.8

jobs:
  set-git-env-vars:
    runs-on: ubuntu-latest
    outputs:
      GIT_COMMIT_SHA: ${{ steps.set-GIT_COMMIT_SHA.outputs.GIT_COMMIT_SHA }}
      GIT_BRANCH: ${{ steps.set-GIT_BRANCH.outputs.GIT_BRANCH }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Get merge commit message
        id: commit-msg
        shell: bash
        run: echo "::set-output name=COMMIT_MSG::$(git log --oneline -n 1 --format='%s')"
        if: github.event_name == 'pull_request'

      - name: Extract commit sha from merge commit msg
        id: commit-sha
        shell: python
        run: |
          import re
          import sys
          sha = re.fullmatch(
              r"^Merge ([a-z0-9]{40}) into [a-z0-9]{40}$",
              "${{ steps.commit-msg.outputs.COMMIT_MSG }}"
          )
          if sha:
              print(f"::set-output name=COMMIT_SHA::{sha.group(1)}")
          else:
              sys.exit(1)
        if: github.event_name == 'pull_request'

      - name: Set GIT_COMMIT_SHA
        id: set-GIT_COMMIT_SHA
        shell: python
        run: |
          if "${{ github.event_name }}" == "pull_request":
              sha = "${{ steps.commit-sha.outputs.COMMIT_SHA }}"
              print("::set-output name=GIT_COMMIT_SHA::{sha}")
          else:
              print("::set-output name=GIT_COMMIT_SHA::${{ github.sha }}")

      - name: Set GIT_BRANCH
        id: set-GIT_BRANCH
        shell: python
        run: |
          branch = "${{ github.ref }}".lstrip("refs/heads/")
          if "${{ github.event_name }}" == "pull_request":
              head_ref = "${{ github.head_ref }}"
              if head_ref:
                  branch = head_ref
          print(f"::set-output name=GIT_BRANCH::{branch}")
```

What I did not test yet and don't know is if the branch name without reference to the fork repository is enough for code-climate.

**Comment by deivid-rodriguez** [comment]
I just [migrated activeadmin](https://github.com/activeadmin/activeadmin/pull/6580) to use https://github.com/paambaati/codeclimate-action, and so far so good. I also tested a PR from an external fork just in case.

In case someone has a good reason to not use the action, you might want to [copy the logic in there](https://github.com/paambaati/codeclimate-action/blob/0f8af43fca84b500025ca48b581bcff933244252/src/main.ts#L39-L57), since it seems like the correct one.

In our case, I thought we couldn't use the action because we were formatting coverage and summing+uploading it in different jobs, but it turns out that wasn't actually necessary and we moved everything to the same place, and the action worked just fine.

**Comment by textbook** [comment]
You don't need a specific action, the latest versions pick up GitHub Actions themselves so you can just run it in a step. 

[Step](https://github.com/textbook/salary-stats/blob/ba4e452154f6569ee246fcda71a90220e6c83919/.github/workflows/push.yml#L24-L26):

```yaml
      - name: Send coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l TypeScript -r ./coverage/lcov.info
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
```

Output:

```none
Run bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l TypeScript -r ./coverage/lcov.info
6
     ______          __
7
    / ____/___  ____/ /___ ________  __
8
   / /   / __ \/ __  / __ `/ ___/ / / /
9
  / /___/ /_/ / /_/ / /_/ / /__/ /_/ /
10
  \____/\____/\__,_/\__,_/\___/\__, /
11
                              /____/
12

13
  Codacy Coverage Reporter
14

15
 --> Download the codacy reporter codacy-coverage-reporter-linux... (latest)
16
#=#=#                                                                         
17
##O#- #                                                                       
18

19
######################################################################## 100.0%
20
#=#=#                                                                         
21
##O#- #                                                                       
22
##O=#  #                                                                      
23

24
################################                                          45.2%
25
######################################################################## 100.0%
26
2020-12-01 22:41:19.105Z  info [ConfigurationRules] API base URL: https://api.codacy.com  - (ConfigurationRules.scala:86)
27
2020-12-01 22:41:19.106Z  info [CommitUUIDProvider] CI/CD provider GitHub Actions found Commit UUID ba4e452154f6569ee246fcda71a90220e6c83919  - (CommitUUIDProvider.scala:130)
28
2020-12-01 22:41:19.106Z  info [ReportRules] Parsing coverage data from: /home/runner/work/salary-stats/salary-stats/./coverage/lcov.info ...  - (ReportRules.scala:43)
29
2020-12-01 22:41:19.111Z  info [ReportRules] Coverage parser used is com.codacy.parsers.implementation.LCOVParser$@21a8038  - (ReportRules.scala:48)
30
2020-12-01 22:41:19.112Z  info [ReportRules] Generated coverage report: /var/tmp/codacy-coverage-18080184524301229960.json (1.98 kB)  - (ReportRules.scala:243)
31
2020-12-01 22:41:19.112Z  info [ReportRules] Uploading coverage data...  - (ReportRules.scala:244)
32
2020-12-01 22:41:19.510Z  info [ReportRules] Coverage data uploaded. Coverage received successfully.  - (ReportRules.scala:158)
33
2020-12-01 22:41:19.510Z  info [CodacyCoverageReporter] All coverage data uploaded.  - (CodacyCoverageReporter.scala:22)
34

35
 --> Succeeded!
```
