### ISSUE TITLE
Coverage reported but not showing

### ISSUE THREAD

**Issue by kpapadatos** [codeclimate/test-reporter#412]
Here you can see the latest reported coverage:
![image](https://user-images.githubusercontent.com/3382344/68070510-f2536d00-fd77-11e9-9cf4-d286294060b3.png)

But it is not showing in the dashboard:
![image](https://user-images.githubusercontent.com/3382344/68070517-0a2af100-fd78-11e9-9136-1d56b8729d66.png)

Even though it is the correct and latest commit in the develop branch:
![image](https://user-images.githubusercontent.com/3382344/68070524-49f1d880-fd78-11e9-8239-3e4ef86ea2bc.png)

**Comment by kpapadatos** [comment]
The same thing is happening in my open source repo https://codeclimate.com/github/Pobuca-Ltd/xsc

**Comment by kpapadatos** [comment]
Just realized branch name was not correct. It was a little confusing since other code analysis tools get it automatically. I'll leave this here for reference: https://docs.codeclimate.com/docs/test-coverage-troubleshooting-branch-names

Using Azure Pipelines I had to do:
```yaml
  - script: |
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
      ./cc-test-reporter upload-coverage
    displayName: Upload coverage to Code Climate
    env:
      CC_TEST_REPORTER_ID: $(frontend-codeclimate-reporter-id)
      GIT_BRANCH: $(Build.SourceBranchName)
      GIT_COMMIT: $(Build.SourceVersion)
```
