### ISSUE TITLE
Alternative GitHub Action

### ISSUE THREAD

**Issue by amancevice** [codeclimate/test-reporter#432]
Hi, I created an alternative GitHub Action for setting up the Code Climate test reporter tool that I wanted to bring to your attention: [amancevice/setup-code-climate](https://github.com/amancevice/setup-code-climate)

I based it on the official tool for using terraform with GitHub Actions. I just wanted to bring it to your attention — I have been using it for my personal projects.

Example usage in a job:

```yaml
- uses: amancevice/setup-code-climate@v0
  with:
    cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
    cc_test_reporter_version: latest  # optional
- run: cc-test-reporter before-build
# ...run test suite...
- run: cc-test-reporter after-build
```

Thanks! Love using Code Climate.
