### ISSUE TITLE
github action: "illegal character code U+0000"

### ISSUE THREAD

**Issue by rrey** [codeclimate/test-reporter#460]
With following workflow on github actions:
```
      - name: Install deps
        run: |
            pip install wheel
            pip install -r requirements.txt

      - name: Pytest
        run: pytest

      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: <my_id>
        with:
          coverageCommand: coverage run --source=. -m pytest
          coverageLocations: |
            ${{github.workspace}}/.coverage:coverage.py
```

I get the following error:

```
/home/runner/work/astuvet-opendata/astuvet-opendata/cc-reporter format-coverage /home/runner/work/astuvet-opendata/astuvet-opendata/.coverage -t coverage.py -o codeclimate.0.json
Error: XML syntax error on line 54: illegal character code U+0000
Usage:
  cc-test-reporter format-coverage [coverage file] [flags]

Flags:
      --add-prefix string   add this prefix to file paths
  -t, --input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov]
  -o, --output string       output path (default "coverage/codeclimate.json")
  -p, --prefix string       the root directory where the coverage analysis was performed (default "/home/runner/work/astuvet-opendata/astuvet-opendata")

Global Flags:
  -d, --debug   run in debug mode

Error: The process '/home/runner/work/astuvet-opendata/astuvet-opendata/cc-reporter' failed with exit code 255
(node:2779) UnhandledPromiseRejectionWarning: Error: The process '/home/runner/work/astuvet-opendata/astuvet-opendata/cc-reporter' failed with exit code 255
    at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:2779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: 🚨 CC Reporter coverage formatting failed!
```

What did I do wrong ?
