### ISSUE TITLE
Test Reporter doesn't take into account my updated .yml file

### ISSUE THREAD

**Issue by williamatpaper** [codeclimate/test-reporter#504]
The first 6 lines of the exclude_pattern section are not getting picked up when I run before-build and after-build. No complex multi test running here.

```
version: "2"
# docs https://docs.codeclimate.com/docs/advanced-configuration
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
exclude_patterns:
  - "app/Providers/BroadcastServiceProvider.php" #not technically application code
  - "app/Exceptions/Handler.php"
  - "app/Http/Controllers/Controller.php"
  - "app/Http/Middleware/TrimStrings.php"
  - "app/Infrastructure/JWT/JWTDecoderInterface.php"
  - "app/Services/LaunchDarkly.php" #this test has to be mocked, and so doesn't get counted for code coverage https://launchdarkly.com/blog/automated-testing-in-launchdarkly/
  - "config/"
  - "docker/"
  - "infra/"
  - "node_modules/"
  - "public/"
  - "dist/"
  - "tests/"
  - "src/assets/"
  - "**/*.spec.js"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  ```
